### ISSUE TITLE
404 via dalle generation

### ISSUE THREAD

**Issue by under1aker** [noes14155/Telegrambot-with-GPT#44]
if you use gpt4free and try to create an image via dalle you will get a 404 error which seems logical, is there a way to generate images without using the naga api and using only gpt4free? 
also img generation with stable diffusion 2.1 doesn't look very good in my opinion. if interested, I changed the endpoint for gradio to "kandinsky-community/kandinsky-2-2-decoder"

**Comment by noes14155** [comment]
better to add a env variable to change endpoint used in gradio?

**Comment by under1aker** [comment]
> better to add a env variable to change endpoint used in gradio?

maybe, this makes sense for a short period of time until dalle 3 is publicly available in october, because all gradiomodels give mediocre results. also i think If gpt4free does not allow to use dallе then we can use naga ai api only to generate images, but responses to text requests will also go through gpt4free in order to bypass the restrictions on requests in naga

**Comment by noes14155** [comment]
added option to change model used in gradio

**Comment by noes14155** [comment]
suggest any other features.
