### ISSUE TITLE
how to get key 

### ISSUE THREAD

**Issue by kaifsarkar123** [noes14155/Telegrambot-with-GPT#45]
how i can get the key gpt4free as I try to join the channel but nothing happens and the telegram link is also not working

**Comment by noes14155** [comment]
If you are using gpt4free no need key. If you use naga api get key from
discord https://discord.gg/GD7VhvSY

**Comment by kaifsarkar123** [comment]
I have tried that but not working I guess I have to put the api base key

**Comment by kaifsarkar123** [comment]
I did not put the back key

**Comment by noes14155** [comment]
If you are using gpt4free no need api_key just change api_base to
http://g4f_server:1337. If you are using naga api_base will be
https://api.naga.ac/v1 and api_key you need to get from discord

**Comment by kaifsarkar123** [comment]
The base url http://g4f_server:1337 is not working when I add the base url the bot doesn't work

**Comment by noes14155** [comment]
API_BASE To use GPT4free API_BASE = 'http://g4f_server:1337' (Only working in docker) You can use any provider. I have included Naga AI api base. Use the key for the same.

Please read the Readme file

**Comment by kaifsarkar123** [comment]
but iam unable to get the nega ai key as I go to the link and tap on join it won't work

**Comment by noes14155** [comment]
Added option to run g4f without docker put API_BASE as http://g4f_server:1337 and remember to update g4f package

**Comment by kaifsarkar123** [comment]
thanks

**Comment by noes14155** [comment]
If you can't get key from naga AI discord use g4f.
