### ISSUE TITLE
TTS and image is not working

### ISSUE THREAD

**Issue by Deplyapp** [noes14155/Telegrambot-with-GPT#48]
TTS is not working I have tried many times but it not work and the image generation is also not working when I type "/img" it every time says "failed to generate images" can you able to solve this for me also it you have deployed the bot can you give me the link so I can test and one more thing how to make the plugins work I have make all the setting such as I have make it true and add all the plugins list but still not work.

**Comment by noes14155** [comment]
dm in telegram i will give you link

**Comment by Deplyapp** [comment]
The Nega ai and the other ai which you provided the link is expired.

**Comment by noes14155** [comment]
updated

**Comment by Deplyapp** [comment]
MandrillaiAI ai not base url

**Comment by noes14155** [comment]
https://api.mandrillai.tech/v1

**Comment by Deplyapp** [comment]
Thanks

**Comment by Deplyapp** [comment]
What is your Telegram username

**Comment by noes14155** [comment]
noes14155
